#!/usr/bin/env bash
# E2E テスト用の .env.local を CloudFormation スタック出力から自動生成するスクリプト
#
# Usage:
#   ./e2e/scripts/setup-env.sh
#   ./e2e/scripts/setup-env.sh --vercel-url https://your-vercel-url.vercel.app
#
# Prerequisites:
#   - AWS CLI configured with appropriate credentials
#   - CloudFormation stack "VoteBoardGameStack" deployed

set -euo pipefail

STACK_NAME="VoteBoardGameStack"
REGION="ap-northeast-1"
ENV_FILE=".env.local"
VERCEL_URL=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --vercel-url)
      VERCEL_URL="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

echo "🔍 Fetching CloudFormation outputs from stack: $STACK_NAME ..."

# Check if stack exists
if ! aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" &> /dev/null; then
  echo "❌ Stack $STACK_NAME not found in region $REGION"
  exit 1
fi

# Get outputs
API_URL=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" --output text)
TABLE_NAME=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='TableName'].OutputValue" --output text)
USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" --output text)

# Validate
for var_name in API_URL TABLE_NAME USER_POOL_ID USER_POOL_CLIENT_ID; do
  val="${!var_name}"
  if [ -z "$val" ] || [ "$val" = "None" ]; then
    echo "❌ $var_name is empty or not found in stack outputs"
    exit 1
  fi
done

echo "✅ CloudFormation outputs retrieved successfully"
echo "   API URL:          $API_URL"
echo "   Table Name:       $TABLE_NAME"
echo "   User Pool ID:     $USER_POOL_ID"
echo "   Client ID:        $USER_POOL_CLIENT_ID"

# Determine BASE_URL
if [ -z "$VERCEL_URL" ]; then
  # Try to read existing BASE_URL from .env.local
  if [ -f "$ENV_FILE" ]; then
    EXISTING_URL=$(grep "^BASE_URL=" "$ENV_FILE" | cut -d'=' -f2- || true)
    if [ -n "$EXISTING_URL" ]; then
      VERCEL_URL="$EXISTING_URL"
      echo "   Base URL:         $VERCEL_URL (from existing $ENV_FILE)"
    fi
  fi
  if [ -z "$VERCEL_URL" ]; then
    VERCEL_URL="https://vote-board-game-web.vercel.app"
    echo "   Base URL:         $VERCEL_URL (default)"
  fi
else
  echo "   Base URL:         $VERCEL_URL (from --vercel-url)"
fi

# Read existing test user credentials if present
TEST_EMAIL=""
TEST_PASSWORD=""
if [ -f "$ENV_FILE" ]; then
  TEST_EMAIL=$(grep "^TEST_USER_EMAIL=" "$ENV_FILE" | cut -d'=' -f2- || true)
  TEST_PASSWORD=$(grep "^TEST_USER_PASSWORD=" "$ENV_FILE" | cut -d'=' -f2- || true)
fi

# Write .env.local
cat > "$ENV_FILE" << ENVEOF
# Auto-generated by e2e/scripts/setup-env.sh
# $(date '+%Y-%m-%d %H:%M:%S')

# Frontend URL (Vercel deployment)
BASE_URL=$VERCEL_URL

# API URL (from CloudFormation)
NEXT_PUBLIC_API_URL=$API_URL

# App URL for OGP image generation
NEXT_PUBLIC_APP_URL=$VERCEL_URL

# DynamoDB Table Name
DYNAMODB_TABLE_NAME=$TABLE_NAME

# Cognito
USER_POOL_ID=$USER_POOL_ID
COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_CLIENT_ID=$USER_POOL_CLIENT_ID

# Test User Credentials (required for authenticated E2E tests)
TEST_USER_EMAIL=$TEST_EMAIL
TEST_USER_PASSWORD=$TEST_PASSWORD

# AWS Region
AWS_REGION=$REGION
ENVEOF

echo ""
echo "✅ $ENV_FILE has been generated"

if [ -z "$TEST_EMAIL" ] || [ -z "$TEST_PASSWORD" ]; then
  echo ""
  echo "⚠️  TEST_USER_EMAIL / TEST_USER_PASSWORD are not set."
  echo "   Edit $ENV_FILE to add test user credentials for authenticated tests."
fi

echo ""
echo "🚀 Ready to run E2E tests:"
echo "   pnpm test:e2e              # all tests"
echo "   pnpm test:e2e:game         # game tests only"
echo "   pnpm test:e2e:headed       # with browser UI"
echo "   pnpm test:e2e:ui           # Playwright UI mode"
